name: Seth Clark
description: Android Developer
avatar: https://avatars1.githubusercontent.com/u/2073653
footer-links:
  email: seth@sethclark.io
  github: setheclark
  twitter: setheclark

url: http://sethclark.io

markdown: redcarpet
highlighter: pygments
permalink: /:title/

version: v1.1.0

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME